// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the MyFirstModule module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aSU_CreateDataBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ASU_CreateData");
		return builder;
	}

	public static boolean aSU_CreateData(IContext context)
	{
		Object result = aSU_CreateDataBuilder().execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_SkeletonHelper_CreateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.DS_SkeletonHelper_Create");
		return builder;
	}

	public static myfirstmodule.proxies.SkeletonHelper dS_SkeletonHelper_Create(IContext context)
	{
		Object result = dS_SkeletonHelper_CreateBuilder().execute(context);
		return result == null ? null : myfirstmodule.proxies.SkeletonHelper.initialize(context, (IMendixObject) result);
	}
}
