// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datagrid.proxies;

public class DataGrid
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dataGridMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DataGrid.DataGrid";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		StringAttribute("StringAttribute"),
		NumberAttribute("NumberAttribute"),
		DateAttribute("DateAttribute"),
		EnumAttribute("EnumAttribute");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DataGrid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected DataGrid(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dataGridMendixObject)
	{
		if (dataGridMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, dataGridMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.dataGridMendixObject = dataGridMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DataGrid.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static datagrid.proxies.DataGrid initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return datagrid.proxies.DataGrid.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static datagrid.proxies.DataGrid initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new datagrid.proxies.DataGrid(context, mendixObject);
	}

	public static datagrid.proxies.DataGrid load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return datagrid.proxies.DataGrid.initialize(context, mendixObject);
	}

	public static java.util.List<datagrid.proxies.DataGrid> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> datagrid.proxies.DataGrid.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of StringAttribute
	 */
	public final java.lang.String getStringAttribute()
	{
		return getStringAttribute(getContext());
	}

	/**
	 * @param context
	 * @return value of StringAttribute
	 */
	public final java.lang.String getStringAttribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.StringAttribute.toString());
	}

	/**
	 * Set value of StringAttribute
	 * @param stringattribute
	 */
	public final void setStringAttribute(java.lang.String stringattribute)
	{
		setStringAttribute(getContext(), stringattribute);
	}

	/**
	 * Set value of StringAttribute
	 * @param context
	 * @param stringattribute
	 */
	public final void setStringAttribute(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String stringattribute)
	{
		getMendixObject().setValue(context, MemberNames.StringAttribute.toString(), stringattribute);
	}

	/**
	 * @return value of NumberAttribute
	 */
	public final java.math.BigDecimal getNumberAttribute()
	{
		return getNumberAttribute(getContext());
	}

	/**
	 * @param context
	 * @return value of NumberAttribute
	 */
	public final java.math.BigDecimal getNumberAttribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.NumberAttribute.toString());
	}

	/**
	 * Set value of NumberAttribute
	 * @param numberattribute
	 */
	public final void setNumberAttribute(java.math.BigDecimal numberattribute)
	{
		setNumberAttribute(getContext(), numberattribute);
	}

	/**
	 * Set value of NumberAttribute
	 * @param context
	 * @param numberattribute
	 */
	public final void setNumberAttribute(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal numberattribute)
	{
		getMendixObject().setValue(context, MemberNames.NumberAttribute.toString(), numberattribute);
	}

	/**
	 * @return value of DateAttribute
	 */
	public final java.util.Date getDateAttribute()
	{
		return getDateAttribute(getContext());
	}

	/**
	 * @param context
	 * @return value of DateAttribute
	 */
	public final java.util.Date getDateAttribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateAttribute.toString());
	}

	/**
	 * Set value of DateAttribute
	 * @param dateattribute
	 */
	public final void setDateAttribute(java.util.Date dateattribute)
	{
		setDateAttribute(getContext(), dateattribute);
	}

	/**
	 * Set value of DateAttribute
	 * @param context
	 * @param dateattribute
	 */
	public final void setDateAttribute(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date dateattribute)
	{
		getMendixObject().setValue(context, MemberNames.DateAttribute.toString(), dateattribute);
	}

	/**
	 * Set value of EnumAttribute
	 * @param enumattribute
	 */
	public final datagrid.proxies.Enumeration_Example getEnumAttribute()
	{
		return getEnumAttribute(getContext());
	}

	/**
	 * @param context
	 * @return value of EnumAttribute
	 */
	public final datagrid.proxies.Enumeration_Example getEnumAttribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.EnumAttribute.toString());
		if (obj == null) {
			return null;
		}
		return datagrid.proxies.Enumeration_Example.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of EnumAttribute
	 * @param enumattribute
	 */
	public final void setEnumAttribute(datagrid.proxies.Enumeration_Example enumattribute)
	{
		setEnumAttribute(getContext(), enumattribute);
	}

	/**
	 * Set value of EnumAttribute
	 * @param context
	 * @param enumattribute
	 */
	public final void setEnumAttribute(com.mendix.systemwideinterfaces.core.IContext context, datagrid.proxies.Enumeration_Example enumattribute)
	{
		if (enumattribute != null) {
			getMendixObject().setValue(context, MemberNames.EnumAttribute.toString(), enumattribute.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.EnumAttribute.toString(), null);
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dataGridMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final datagrid.proxies.DataGrid that = (datagrid.proxies.DataGrid) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
